#!/usr/bin/fish

set projects ""

for i in ~/.tmuxinator/*
  set projects $projects(echo (basename $i .yml)"\n")
end

set project (echo -e $projects | dmenu -p "TMUX workspace")

if [ -z $project ]
  exit
end

mux $project
