#!/bin/zsh

# BATTERY
print_battery() {
  BATPATH=/sys/class/power_supply/BAT0
  if [ ! -d $BATPATH ]; then
    BATPATH=/sys/class/power_supply/BAT1
  fi
  STATUSPATH=$BATPATH/status
  BAT_FULL=$BATPATH/charge_full
  if [ ! -r $BAT_FULL ]; then
    BAT_FULL=$BATPATH/energy_full
  fi
  BAT_NOW=$BATPATH/charge_now
  if [ ! -r $BAT_NOW ]; then
    BAT_NOW=$BATPATH/energy_now
  fi

  bf=$(cat $BAT_FULL)
  bn=$(cat $BAT_NOW)
  st=$(cat $STATUSPATH)
  pct=$((100 * $bn / $bf))

  case $st in
    "Charging") sign="+" ;;
    "Discharging") sign="↓" ;;
    "Full") sign="-" ;;
    *) sign="$st" ;; 
  esac

  if [ "$pct" -lt 5 ]; then color="#[fg=red]"
  elif [ "$pct" -lt 20 ]; then color="#[fg=yellow]"
  else color="#[fg=blue]"
  fi

  printf "#[fg=blue]Battery %s %s" "$pct%" "$color$sign"
}

# TEMPERATURE
print_temperature() {
  input=/sys/class/hwmon/hwmon0/temp1_input
  [ -s "$input" ] && temperature=$(awk '{printf "%0.f",$1/1000}' "$input")
  if [ -n "$temperature" ]; then
    if [ "$temperature" -gt 69 ]; then modifier="#[fg=red]"
    elif [ "$temperature" -gt 62 ]; then modifier="#[fg=yellow]"
    elif [ "$temperature" -gt 54 ]; then modifier="#[fg=green]"
    else modifier="#[fg=blue]"
    fi
    printf "#[fg=blue]Temp %s°#[default]" "$modifier$temperature"
  fi
}

# MEMORY
print_memory() {
  memory=$(free | awk '/buffers\/cache:/ {printf "%.0f", 100*$3/($3 + $4)}')
  if [ "$memory" -gt 90 ]; then modifier="#[fg=red]"
  elif [ "$memory" -gt 80 ]; then modifier="#[fg=yellow]"
  elif [ "$memory" -gt 70 ]; then modifier="#[fg=green]"
  else modifier="#[fg=blue]"
  fi
  printf "#[fg=blue]RAM %s%s%%#[default]" "$modifier" "$memory"
}

# GERMAN DATE
print_date() {
  printf "#[fg=colour12]$(date +"%a %b %d") $(date +"%H:%M")#[default]"
}

echo "$(print_battery)   $(print_temperature)   $(print_memory)   $(print_date)"
