#!/bin/zsh
# 0 black
# 1 red
# 2 green
# 3 yellow
# 4 blue
# 5 pink
# 6 cyan
# 9 orange
# black -> white 8 0 10 11 12 14 7 15 

separator=" #[fg=blue]- #[default]"

# BATTERY
infos=$(acpi -b)
percent=$(echo $infos|sed "s/Battery .: [a-z]*, \([0-9]*\)%\(,.*\|$\)/\1/i")
state=$(echo $infos|sed "s/Battery .: \([a-z]*\),.*/\1/i")
if [ "$percent" -lt 5 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
elif [ "$percent" -lt 20 ]; then modifier="#[bg=colour3,fg=colour8,bright]"
elif [ "$percent" -lt 50 ]; then modifier="#[fg=colour3]"
else modifier="#[fg=colour2]"
fi
percent="$percent%"
case $state in
  "Charging") sign="|+|"; modifier="#[fg=green]" ;;
"Discharging") sign="|-|" ;;
    "Full") sign="⚡"; percent= ;;
  *) sign="$state" ;;
esac
printf "#[fg=blue]⚡ $modifier%s%s#[default]" "$percent" "$sign"

printf $separator

# TEMPERATURE
input=/sys/class/hwmon/hwmon0/temp1_input
[ -s "$input" ] && temperature=$(awk '{printf "%0.f",$1/1000}' "$input")
if [ -n "$temperature" ]; then
  if [ "$temperature" -gt 69 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
  elif [ "$temperature" -gt 62 ]; then modifier="#[fg=colour13,bright]"
  elif [ "$temperature" -gt 54 ]; then modifier="#[fg=colour6]"
  else modifier="#[fg=colour4]"
  fi
  printf "#[fg=blue]☢ %s%s°#[default]" "$modifier" "$temperature"
fi

printf $separator

# MEMORY
memory=$(free | awk '/buffers\/cache:/ {printf "%.0f", 100*$3/($3 + $4)}')
if [ "$memory" -gt 90 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
elif [ "$memory" -gt 80 ]; then modifier="#[bg=colour3,fg=colour0]"
elif [ "$memory" -gt 70 ]; then modifier="#[fg=colour9]"
else modifier="#[fg=colour2]"
fi
printf "#[fg=blue]♺ %s%s%%#[default]" "$modifier" "$memory"

printf $separator

# GERMAN DATE
#export TZ="Europe/Berlin"
printf " #[fg=colour12]$(date +"%a %b %d") $(date +"%H:%M")#[default]"
